name: sdxl_comparison
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - pytorch-cuda=12.1  # GPU acceleration (remove if CPU-only)
  - pip
  - pip:
      - torchmetrics>=1.3.0
      - diffusers>=0.29.0
      - transformers>=4.41.0
      - accelerate>=0.31.0
      - huggingface-hub>=0.23.0
      - datasets>=2.19.0
      - Pillow>=10.0.0
      - matplotlib>=3.8.0
      - numpy>=1.26.0
      - scipy>=1.12.0
      - tqdm>=4.66.0
